app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import Home, Blog, About, blog_tags, Scholarship, Contact, blog_detail, Single, ItemListView, search, \
    subscribe

urlpatterns = [
    path("", Home, name='Home'),
    path("blog/", Blog, name='Blog'),
    path('blog/<int:pk>/',blog_detail, name='view'),
    # path('blog/<int:pk>/add_comment/', add_comment, name='add_comment'),
    # path('comment/<int:pk>/add_reply/', add_reply, name='add_reply'),
    path("about", About, name='About'),
    path("scholarship", Scholarship, name='Scholarship'),
    path("contact", Contact, name='Contact'),
    path("single", Single),
    path('filter/', ItemListView.as_view(), name='item-list'),
    path('tag/<slug:tag_slug>', blog_tags, name='tag'),
    # path("contact-test", Contact_Test, name='Contact'),
    path('success/', TemplateView.as_view(template_name='success_page.html'), name='success'),
    path('search/', search, name='search'),
    path('subscribe/', subscribe, name ='subscribe')

]

eduweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager

TAG_CHOICES = [
    ('University', 'University'),
    ('Jamb', 'Jamb'),
    ('Education', 'Education'),
    ('News', 'News'),
    ('Science', 'Science'),
    ('Admission', 'Admission')

]


class Blogs(models.Model):
    img_url = models.CharField(max_length=2083, default="")
    title = models.CharField(max_length=1000)
    authour = models.CharField(max_length=500)
    desc = models.CharField(max_length=500, default="")
    authour_img = models.CharField(default="", max_length=2084)
    tags = TaggableManager()
    body = RichTextField(blank=True, null=True)
    date = models.DateField()
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(Blogs, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    email = models.EmailField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)


class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    email = models.EmailField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)

    # def get_absolute_url(self):
    #     return reverse('view', args=(str(self.slug)))

class Ad(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='ads/')
    url = models.URLField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
class Subscriber(models.Model):
    email= models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return  self.email
class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

app/forms.py
from django import forms
from .models import Comment, Reply, Subscriber


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'email', 'author']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['text',  'author']


class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    email = forms.EmailField(label='Your Email')
    subject = forms.CharField(label='Subject', max_length=200)
    message = forms.CharField(label='Your Message', widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False,label='Search')


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields= ['email']

app/templates/ad_popup.html
<!-- ad_popup.html -->
{% if ad %}
<div id="ad-popup">
    <div class="popup-content">
                <span id="close-popup" class="close-button">&times;</span>
        <a href="{{ ad.url }}" target="_blank">
            <img src="{{ ad.image.url }}"  alt="{{ ad.title }}">
        </a>
    </div>
</div>
{% endif %}

app/templates/category.html
{%extends 'base.html'%}
{%block content%}
<br>

<ul class="container">
    <div class="row">
        {%for post in post%}

     <div class="col-lg-4">
                        <div class="position-relative mb-3">
                            <img class="img-fluid w-100" src="{{post.img_url}}" style="object-fit: cover; height: 300px;">
                            <div class="bg-white border border-top-0 p-4">
                                <div class="mb-2">
                                                                           {%for tag in post.tags.all%}
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2" href="">{{tag.name}}</a>
                                    {%endfor%}
                                    <a class="text-body" href=""><small>{{post.date}}</small></a>
                                </div>
                                <a class="h4 d-block mb-3 text-secondary text-uppercase font-weight-bold" href="{%url 'view' post.pk%}">{{post.title}}</a>
                                <p class="m-0">{{post.desc}}</p>
                            </div>
                            <div class="d-flex justify-content-between bg-white border border-top-0 p-4">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle mr-2" src="{{post.authour_img}}" width="25" height="25" alt="">
                                    <small>{{post.authour}}</small>
                                </div>
                                <div class="d-flex align-items-center">
                                    <small class="ml-3"><i class="far fa-eye mr-2"></i>{{post.view_count}}</small>
                                    <small class="ml-3"><i class="far fa-comment mr-2"></i>{{post.num_comments}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
            {%endfor%}

        </div>

<nav aria-label="...">
     <ul class="pagination">
<!--    <span class="step-links">-->

        {% if post.has_previous %}
         <li class="page-item">
            <a class="page-link" href="?page={{ post.previous_page_number }}">Previous</a>
                    </li>

        {% endif %}
         <li class="page-item">
                  <a class="page-link" href="?page=1">1</a>
         </li>

         <li class="page-item">
                  <a class="page-link" href="?page=2">2</a>
         </li>

         <li class="page-item">
                  <a class="page-link" href="?page=3">3</a>
         </li>
        {% if post.has_next %}
         <li  class="page-item">
            <a class="page-link" href="?page={{ post.next_page_number }}">Next   </a>
<!--            <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>-->
      </li>
        {% endif %}
         <br>
         <h5>
           <span class="current">
              Page {{ post.number }} of {{ post.paginator.num_pages }}.
           </span></h5>
<!--    </span>-->
  </ul>
</nav>
        </div>

{%endblock%}

app/templates/contact.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    <!-- Contact Start -->
    <div class="container-fluid mt-5 pt-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Get in Tourch with us </h4>
                    </div>
                    <div class="bg-white border border-top-0 p-4 mb-3">
                        <div class="mb-4">
                            <h6 class="text-uppercase font-weight-bold">Contact Info</h6>
                            <p class="mb-4">Contact us at Legit Edu Consults for your updates on admission, Jamb News, Institutions, and education trendings as a whole. Our support desk is available 24/7. <br>We serve you the best you'll ever think of.
            							<div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-map-marker-alt text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Our Office</h6>
                                </div>
                                <p class="m-0">Temporarily Lasustech Isolo Campus</p>
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-envelope-open text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Email Us</h6>
                                </div>
                                <p class="m-0">www.legiteduconsults@gmail.com</p>
                            </div>
                            <div class="mb-3">
                                <div class="d-flex align-items-center mb-2">
                                    <i class="fa fa-phone-alt text-primary mr-2"></i>
                                    <h6 class="font-weight-bold mb-0">Call Us</h6>
                                </div>
                                <p class="m-0">+234 907 945 3337, 08142069709</p>
                            </div>
                        </div>
                        <h6 class="text-uppercase font-weight-bold mb-3">Contact Us</h6>
<!--                       <form method="post">-->
<!--                           {%csrf_token%}-->
<!--                           {{form.as_p}}-->
<!--                           <button type="submit">send</button>-->
<!--                       </form>-->
                        <form method="post">
                        {%csrf_token%}
                     <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                            <input type="text" name="name" class="form-control p-4" maxlength="100" placeholder="Your Name" required id="id_name">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                            <input type="email" name="email" class="form-control p-4" placeholder="Your Email"maxlength="320" required id="id_email">

                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" name="subject" class="form-control p-4" placeholder="Subject" maxlength="200" required id="id_subject">
                            </div>
                            <div class="form-group">
                                <textarea name="message" class="form-control" rows="4" placeholder="Message"  cols="40" rows="10" required id="id_message"></textarea>
                            </div>
                            <div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;"
                                    type="submit">Send Message</button>
                            </div>
<!--                      <form method="post">-->
<!--                            <input type="hidden" name="csrfmiddlewaretoken" value="6k3OnHaOwPChlnZuvCGNQ8Z1Mzt8mrjIJhtYUws0PUDzG4SYNCt11Uu89kuMIenu">-->
<!--                            <p>-->
<!--    <label for="id_name">Your Name:</label>-->
<!--    <input type="text" name="name" maxlength="100" required id="id_name">-->
<!--  </p>-->
<!--  <p>-->
<!--    <label for="id_email">Your Email:</label>-->
<!--    <input type="email" name="email" maxlength="320" required id="id_email">-->
<!--  </p>-->
<!--  <p>-->
<!--    <label for="id_subject">Subject:</label>-->
<!--    <input type="text" name="subject" maxlength="200" required id="id_subject">-->
<!--  </p>-->
<!--  <p>-->
<!--    <label for="id_message">Your Message:</label>-->
<!--    <textarea name="message" cols="40" rows="10" required id="id_message">-->
<!--</textarea>-->

<!--  </p>-->
<!--                            <button type="submit">send message</button>-->
<!--                        </form>-->
                    </div>
                </div>
                <div class="col-lg-4">
                    <!-- Social Follow Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Follow Us</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                                <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">1000+ Fans</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                                <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">500+ Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                                <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">550+ Connects</span>
                            </a>
                            <a href="https://www.instagram.com/legit_edu_consults/" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                                <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">1000 Followers</span>
                            </a>
                            
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                                <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">3,000 Subscribers</span>
                            </a>
                            <!-- <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                                <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span> -->
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}

app/templates/contact_test.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

app/templates/search.html
{%extends 'base.html'%}
{%block content%}

<h3>Search results for "{{query}}"</h3>

<br><br>
<!--<div class="container">-->
    <div class="container">
<div class="row">
    {%for results in results%}
          <div class="col-lg-4">
                        <div class="position-relative mb-3">
                            <img class="img-fluid w-100" src="{{results.img_url}}" style="object-fit: cover; height: 300px;">
                            <div class="bg-white border border-top-0 p-4">
                                <div class="mb-2">
                                                                           {%for tag in results.tags.all%}
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2" href="">{{tag.name}}</a>
                                    {%endfor%}
                                    <a class="text-body" href=""><small>{{results.date}}</small></a>
                                </div>
                                <a class="h4 d-block mb-3 text-secondary text-uppercase font-weight-bold" href="{%url 'view' results.pk%}">{{results.title}}</a>
                                <p class="m-0">{{results.desc}}</p>
                            </div>
                            <div class="d-flex justify-content-between bg-white border border-top-0 p-4">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle mr-2" src="{{latest.authour_img}}" width="25" height="25" alt="">
                                    <small>{{results.authour}}</small>
                                </div>
                                <div class="d-flex align-items-center">
                                    <small class="ml-3"><i class="far fa-eye mr-2"></i>{{results.view_count}}</small>
                                    <small class="ml-3"><i class="far fa-comment mr-2"></i>123</small>
                                </div>
                            </div>
                        </div>
                    </div>
        {%empty%}
        <form method="get" action="{%url 'search'%}">
            <div class="input-group">
        <input class ="form-control" type="text" name="query" id="" placeholder="Search....">
        <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
    </form>

{%endfor%}

{%endblock%}
</div>
</div>

app/templates/single.html
{% extends "base.html" %}
{%block content %}
<head>
      <meta property="og:title" content="{{ Blog.title }}" />
    <meta property="og:description" content="{{ Blog.excerpt }}" />
    <meta property="og:image" content="{{ Blog.img_url }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
</head>
<!-- Breaking News Start -->
    <div class="container-fluid mt-5 mb-3 pt-3">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="d-flex justify-content-between">
                        <div class="section-title border-right-0 mb-0" style="width: 180px;">
                            <h4 class="m-0 text-uppercase font-weight-bold">Trending</h4>
                        </div>
                        <div class="owl-carousel tranding-carousel position-relative d-inline-flex align-items-center bg-white border border-left-0"
                            style="width: calc(100% - 180px); padding-right: 100px;">
                            {%for trending in trending%}
                            <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">{{trending.title}}</a></div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breaking News End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- News Detail Start -->
                    <div class="position-relative mb-3">
                        <img class="img-fluid w-100" src="{{Blog.img_url}}" style="object-fit: cover;">
                        <div class="bg-white border border-top-0 p-4">
                            <div class="mb-3">
                                <a class="badge badge-primary text-uppercase font-weight-semi-bold p-2 mr-2"
                                    href="">{{Blog.tag}}</a>
                                <a class="text-body" href="">{{Blog.date}}</a>
                            </div>
                            <h1 class="mb-3 text-secondary text-uppercase font-weight-bold">{{Blog.title}}</h1>
                           <div> {{Blog.body|safe}}</div>
                          
                        </div>
                        <div class="d-flex justify-content-between bg-white border border-top-0 p-4">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle mr-2" src="{{Blog.authour_img}}" width="25" height="25" alt="">
                                <span>{{Blog.authour}}</span>
                            </div>
                            <div class="d-flex align-items-center">
                                <span class="ml-3"><i class="far fa-eye mr-2"></i>{{Blog.view_count}}</span>
                                <span class="ml-3"><i class="far fa-comment mr-2"></i>{{num_comments}}</span>
                            </div>
                        </div>
                    </div>
                    <!-- News Detail End -->

                    <!-- Comment List Start -->
                    <div class="mb-3">

                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold"> Comments</h4>
                        </div>
   {%for comment in comments %}
                        <div class="bg-white border border-top-0 p-4">
                            <div class="media">
                                <i class="fas fa-user-circle mr-3"></i>
                                <div class="media-body">
                                    <h6><a class="text-secondary font-weight-bold" href="">{{comment.author}}</a> <small><i>{{comment.date}}</i></small></h6>
                                    <p>{{comment.text}}</p>
                                </div>
                            </div>
                        </div>
                        {%endfor%}

                    </div>
                    <!-- Comment List End -->

                    <!-- Comment Form Start -->


                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Leave a comment</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-4">

                        <form method="post" >
                            {%csrf_token%}
                            <div class="form-row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                          <label for="id_author">Name:</label>
                                    <input type="text" name="author" class="form-control" maxlength="50" required id="id_author">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="id_email">Email:</label>
                                    <input type="email" name="email" class="form-control" maxlength="200" required id="id_email">
                                        </div>
                                    </div>
                                </div>
<!--                                <div class="form-group">-->
<!--                                    <label for="website">Website</label>-->
<!--                                    <input type="url" class="form-control" id="website">-->
<!--                                </div>-->

                                <div class="form-group">
                                  <label for="id_text">Message:</label>
    <textarea name="text" cols="40" class="form-control" rows="10" required id="id_text">
</textarea>
                                </div>
                                <div class="form-group mb-0">
                                     <input type="submit" value="Add Comment"
                                        class="btn btn-primary font-weight-semi-bold py-2 px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- Comment Form End -->
                </div>

                <div class="col-lg-4">
                    <!-- Social Follow Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Follow Us</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                                <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Fans</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                                <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                                <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Connects</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                                <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                                <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Subscribers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                                <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                    <!-- Ads Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Advertisement</h4>
                        </div>
                        <div class="bg-white text-center border border-top-0 p-3">
                            <a href=""><img class="img-fluid" src="img/news-800x500-2.jpg" alt=""></a>
                        </div>
                    </div>
                    <!-- Ads End -->

                <!-- Popular News Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Trending News</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        {%for trending in trending %}
                        <div class="d-flex align-items-center bg-white mb-3" style="height: 110px;">
                            <img class="img-fluid" src="trending.img_url" alt="">
                            <div class="w-100 h-100 px-3 d-flex flex-column justify-content-center border border-left-0">
                                <div class="mb-2">
                                    {%for tag in trending.tags.all%}
                                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">{{tag.name}}</a>
                                    {%endfor%}
                                    <a class="text-body" href=""><small>{{trending.date}}</small></a>

                                </div>
                                <a class="h6 m-0 text-secondary text-uppercase font-weight-bold" href="{%url 'view' trending.pk%}">{{trending.title}}</a>
                            </div>
                        </div>
                        {%endfor%}


                <!-- Tags Start -->
                <div class="mb-3">
                    <div class="section-title mb-0">
                        <h4 class="m-0 text-uppercase font-weight-bold">Tags</h4>
                    </div>
                    <div class="bg-white border border-top-0 p-3">
                        <div class="d-flex flex-wrap m-n1">

                            <a href="{%url 'tag' tag_slug='university'%}" class="btn btn-sm btn-outline-secondary m-1">Universiity</a>
                            <a href="{%url 'tag' tag_slug='jamb'%}" class="btn btn-sm btn-outline-secondary m-1">Jamb</a>
                            <a href="{%url 'tag' tag_slug='politics'%}" class="btn btn-sm btn-outline-secondary m-1">Politics</a>
                            <a href="{%url 'tag' tag_slug='football'%}" class="btn btn-sm btn-outline-secondary m-1">Football</a>



                        </div>
                    </div>
                </div>
                <!-- Tags End -->                </div>
            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->

{%endblock%}

app/templates/subscribe.html
{% extends 'base.html' %}

{% block content %}
<h2>Subscribe to our Newsletter</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Subscribe</button>
</form>
{% endblock %}

app/templates/success_page.html
{% extends "base.html" %}
{% block content %}
<h2>Thank you!</h2>
<p>You have successfully contacted. <span>Thanks</span> </p>
<span>TEAM LEGIT EDU</span>
{% endblock %}